name = "cpc-checker"
defaultTargets = ["Checker", "Definitions", "checker"]
precompileModules = true

[[lean_lib]]
name = "Checker"

[[lean_lib]]
name = "Definitions"

[[lean_exe]]
name = "checker"
root = "Main"
supportInterpreter = true

[[require]]
name = "smt"
git = "https://github.com/abdoo8080/lean-smt"
rev = "6973d5f3ea37afd8745abd90008506bb2a046da4"
