name = "cpc-checker"
defaultTargets = ["Checker", "checker"]
precompileModules = true

[[lean_lib]]
name = "Checker"

[[lean_exe]]
name = "checker"
root = "Main"
supportInterpreter = true

[[require]]
name = "smt"
git = "https://github.com/abdoo8080/lean-smt"
rev = "01e22537dadfd9af71b0ec1efe5cf33e7140dfdf"
